version: '3.6'
services:
  mysql-service:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=capstonedb
    ports:
      - 3307:3306
    networks:
      - private
    restart: always
  spring-boot-service:
    image: akashkale/spring-boot-app:c1
    #build: ./backend/Login-app-micro-service/Login-app-micro-service/
    container_name: spring_boot_container
    ports:
      - 8181:8181
    depends_on:
      - mysql-service
    networks:
      - private
      - public 
    restart: always
  angular-service:
    image: akashkale/angular-framework-app:c1
    #build: ./frontend/shopping-frontend-app/
    container_name: angular_container
    ports:
      - 8282:80
    networks:
      - public  
networks:
  private :
    name : spring-boot-mysql-network 
  public:
    name : angular-and-spring-boot-network