version: '3.6'
services:
  mysql-service:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=capstonedb
    ports:
      - 3307:3306
    restart: always
  spring-boot-service:
    #image: imageName
    build: ./backend/Login-app-micro-service/Login-app-micro-service/
    container_name: spring_boot_container
    ports:
      - 8181:8181
    depends_on:
      - mysql-service
    restart: always
  angular-service:
    build: ./frontend/shopping-frontend-app/
    container_name: angular_container
    ports:
      - 8282:80 
