version: '3.6'
services:
  mysql-service:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=capstonedb
    ports:
      - 3307:3306
    networks:
      - private
    restart: always
  spring-boot-service:
    image: spring-boot-app
    build: ./backend/Login-app-micro-service/Login-app-micro-service/
    container_name: spring_boot_container
    ports:
      - 8181:8181
    depends_on:
      - mysql-service
    networks:
      - private
    restart: always
  angular-service:
    image: angular-framework-app
    build: ./frontend/shopping-frontend-app/
    container_name: angular_container
    ports:
      - 8282:80 
networks:
  private :
    name : spring-boot-mysql-network 